/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recordmanagementsystem;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author MAX
 */
public class ViewData extends javax.swing.JFrame {

    private final int titleCol = 0;
    private final int dateCol = 1;
    private final int descCol = 2;
    private final int remCol = 3;
    
    DateFormat dateFormat = new SimpleDateFormat("MM/dd/YY");
    Date date = new Date();
    Calendar cal = Calendar.getInstance();
    public ViewData() {
        super.setLocation(380, 150);
        super.setResizable(false);
        super.setVisible(true);
        
        
        initComponents();
        
        TitleField.setText((String) Database.model.getValueAt(Database.recordTable.getSelectedRow(), titleCol));
        DescriptionField.setText((String)Database.model.getValueAt(Database.recordTable.getSelectedRow(), descCol));
        RemarksField.setText((String) Database.model.getValueAt(Database.recordTable.getSelectedRow(), remCol));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TitleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editdoneButton = new javax.swing.JButton();
        backcancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        RemarksField = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        Mode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Title");

        TitleField.setEditable(false);
        TitleField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TitleField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TitleField.setAlignmentX(0.0F);
        TitleField.setAlignmentY(0.0F);
        TitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Remarks");

        editdoneButton.setText("Edit");
        editdoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdoneButtonActionPerformed(evt);
            }
        });

        backcancelButton.setText("Back");
        backcancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backcancelButtonActionPerformed(evt);
            }
        });

        DescriptionField.setEditable(false);
        DescriptionField.setColumns(20);
        DescriptionField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        DescriptionField.setRows(5);
        jScrollPane1.setViewportView(DescriptionField);

        RemarksField.setEditable(false);
        RemarksField.setColumns(20);
        RemarksField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        RemarksField.setRows(5);
        jScrollPane2.setViewportView(RemarksField);

        Mode.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Mode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mode.setText("View");
        Mode.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backcancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(editdoneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TitleField)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editdoneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backcancelButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TitleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleFieldActionPerformed
        
    }//GEN-LAST:event_TitleFieldActionPerformed

    private void editdoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdoneButtonActionPerformed
        if ("Edit".equals(editdoneButton.getText())) {
            TitleField.setEditable(true);
            DescriptionField.setEditable(true);
            RemarksField.setEditable(true);
            
            Mode.setText("Edit");
            editdoneButton.setText("Done");
            backcancelButton.setText("Cancel");
        }else if("Done".equals(editdoneButton.getText())){
            if (TitleField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a title", "Missing Title", JOptionPane.ERROR_MESSAGE);
        }else
            if (DescriptionField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add a description", "Missing Description", JOptionPane.ERROR_MESSAGE);
        }else{
        Database.model.setValueAt(TitleField.getText(), Database.recordTable.getSelectedRow(), titleCol);
        Database.model.setValueAt(dateFormat.format(date), Database.recordTable.getSelectedRow(), dateCol);
        Database.model.setValueAt(DescriptionField.getText(), Database.recordTable.getSelectedRow(), descCol);
        Database.model.setValueAt(RemarksField.getText(), Database.recordTable.getSelectedRow(), remCol);
        
        TitleField.setEditable(false);
        DescriptionField.setEditable(false);
        RemarksField.setEditable(false);
        
        Mode.setText("View");
        editdoneButton.setText("Edit");
        backcancelButton.setText("Back");
            }
        }
    }//GEN-LAST:event_editdoneButtonActionPerformed

    private void backcancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backcancelButtonActionPerformed
        if ("Back".equals(backcancelButton.getText())) {
            super.dispose();
        }else if("Cancel".equals(backcancelButton.getText())){
            TitleField.setEditable(false);
            DescriptionField.setEditable(false);
            RemarksField.setEditable(false);
            
            Mode.setText("View");
            editdoneButton.setText("Edit");
            backcancelButton.setText("Back");
        }
    }//GEN-LAST:event_backcancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewData().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescriptionField;
    private javax.swing.JLabel Mode;
    private javax.swing.JTextArea RemarksField;
    private javax.swing.JTextField TitleField;
    private javax.swing.JButton backcancelButton;
    private javax.swing.JButton editdoneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
